version: '3.8'

services:

  web:
    build: ./project
    ports:
      - 8962:8000
    command: conda run -n xv2_backend uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./project:/usr/src/app
      - ./temp:/temp
      - ./data:/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./project
    command: conda run -n xv2_backend celery --app=worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./project:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  dashboard:
    build: ./project
    command: conda run -n xv2_backend celery --broker=redis://redis:6379/0 --app=worker.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
