name: xv2_backend
channels:
  - conda-forge
  - defaults
dependencies:
  - planet
  - gdal
  - geopandas
  - osmnx
  - xmltodict
  - pydantic
  - python=3.9
  - opencv
  - mercantile
  - psycopg2
  - sqlalchemy