# hello_sky.yaml

resources:
  # Optional; if left out, pick from the available clouds.
  cloud: aws
  use_spot: true
  # 1x NVIDIA V100 GPU
  # accelerators: V100:8

# Working directory (optional) containing the project codebase.
# Its contents are synced to ~/sky_workdir/ on the cluster.
workdir: .

file_mounts:
  /input_pre:
  /input_post: ~
  /input_poly: ~

  /output:
    name: xv2-outputs
    mode: MOUNT

# Typical use: pip install -r requirements.txt
# Invoked under the workdir (i.e., can use its files).
setup: |
  echo "Running setup."
  aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 316880547378.dkr.ecr.us-east-2.amazonaws.com
  docker pull 316880547378.dkr.ecr.us-east-2.amazonaws.com/xview:latest

# Typical use: make use of resources, such as running training.
# Invoked under the workdir (i.e., can use its files).
run: |
  pwd
  ls -la /s3
  # docker run --rm 316880547378.dkr.ecr.us-east-2.amazonaws.com/xview:latest
  # sudo shutdown -h now